### ISSUE TITLE
[Java] serializing Scala Enumerations is complicated 

### ISSUE THREAD

**Issue by pjfanning** [alipay/fury#1024]
**Describe the bug**
https://www.scala-lang.org/api/2.13.x/scala/Enumeration.html is not a popular feature in Scala but it exists. Scala 3 has a new enum class (as well as the scala.Enumeration). Enumeratum is a popular 3rd party lib.

I found serializing scala.Enumeration instances awkward.

I get an exception unless I register scala.Enumeration.Val class and this is not public. I had to create a hacky class in Java to access it.

https://github.com/pjfanning/fury-scala-test/blob/a6585dc407ac2f15f09352aec1f85025c24adf2f/src/main/java/scala/FuryUtils.java

I also had to register the scala.runtime.ModuleSerializationProxy

https://github.com/pjfanning/fury-scala-test/blob/a6585dc407ac2f15f09352aec1f85025c24adf2f/src/test/scala/io/github/pjfanning/fury/FuryTest.scala#L26-L33

**Expected behavior**

If and when Fury adds specialized Scala support, making this easier should be considered.

**Comment by chaokunyang** [comment]
You  may need to create fury with `requireClassRegistration(false)`:
```scala
val fury = Fury.builder().withLanguage(Language.JAVA).requireClassRegistration(false).build()
```
We enabled `requireClassRegistration` by default to avoid deserializing insecure types. This is a common vulnerability in dynamic serialization frameworks in JDK/Hessian/FST and so on. Without this option, we must add insecure classes to blacklist, but those classes are unknown and too much to add.

Actually, I think we need to add more detailed exception to tell users to `requireClassRegistration(false)` if the env is secure.

**Comment by chaokunyang** [comment]
Is https://github.com/pjfanning/fury-scala-test/blob/a6585dc407ac2f15f09352aec1f85025c24adf2f/src/main/java/scala/FuryUtils.java in a private repo?  Seems inaccessible

**Comment by pjfanning** [comment]
@chaokunyang I have made the repo public now. I thought it was already public. I have discovered that the code doesn't need to be the `scala` package. My IDE (IntelliJ) doesn't like it but my sbt build works if I move the class to a different package. https://github.com/pjfanning/fury-scala-test/blob/5c2023e2f8d5e1cd6f599ad65c4134498517dddd/src/main/java/io/github/pjfanning/fury/FuryUtils.java

**Comment by chaokunyang** [comment]
@pjfanning Yeah, I can access it now. With `requireClassRegistration(false)` set, no registration is needed now:
![image](https://github.com/alipay/fury/assets/12445254/e4e49d42-3add-4e33-bb32-99252d8f0387)
