### ISSUE TITLE
[JavaScript] deserialization error when object contains binary

### ISSUE THREAD

**Issue by 3tieto** [alipay/fury#1025]
![image](https://github.com/alipay/fury/assets/147470591/78ea2022-6996-4bbb-a5f2-9129ff06781d)

如上图

测试代码
```
var bf, deserialize, fury, obj, result, serialize;

import {
  Type,
  default as Fury
} from '@furyjs/fury';

console.log(Type);

fury = new Fury.default({
  refTracking: true
});

({serialize, deserialize} = fury.registerSerializer(Type.object("example.foo", {
  foo: Type.any(),
  bar: Type.any(),
  map: Type.map(Type.any(), Type.any()),
  set: Type.set(Type.any()),
  list: Type.array(Type.any()),
  binary: Type.binary()
})));

obj = {
  foo: "123",
  bar: 123,
  map: new Map([["hello", 1], ["world", 2]]),
  set: new Set([1, 2, "123"]),
  list: ["123", 123, true],
  binary: new Uint8Array([1, 2, 3])
};

bf = serialize(obj);

result = deserialize(bf);

console.log(result);

```

**Comment by wangweipeng2** [comment]
> ![image](https://user-images.githubusercontent.com/147470591/277880059-78ea2022-6996-4bbb-a5f2-9129ff06781d.png)
> 
> 如上图
> 
> 测试代码
> 
> ```
> var bf, deserialize, fury, obj, result, serialize;
> 
> import {
>   Type,
>   default as Fury
> } from '@furyjs/fury';
> 
> console.log(Type);
> 
> fury = new Fury.default({
>   refTracking: true
> });
> 
> ({serialize, deserialize} = fury.registerSerializer(Type.object("example.foo", {
>   foo: Type.any(),
>   bar: Type.any(),
>   map: Type.map(Type.any(), Type.any()),
>   set: Type.set(Type.any()),
>   list: Type.array(Type.any()),
>   binary: Type.binary()
> })));
> 
> obj = {
>   foo: "123",
>   bar: 123,
>   map: new Map([["hello", 1], ["world", 2]]),
>   set: new Set([1, 2, "123"]),
>   list: ["123", 123, true],
>   binary: new Uint8Array([1, 2, 3])
> };
> 
> bf = serialize(obj);
> 
> result = deserialize(bf);
> 
> console.log(result);
> ```
Thank you so much for submitting this , i will take a investigate.

**Comment by wangweipeng2** [comment]
@3tieto  I tried to fix the issue, and publish a new version of  "@furyjs/fury": "0.3.0-beta.1" could you help me test it on your machine ?
