### ISSUE TITLE
[Java] NPE serializing Scala 3 enum

### ISSUE THREAD

**Issue by pjfanning** [alipay/fury#1033]
Fury 0.2.1. Scala 3 has a new type of enum - different from the Scala 2 Enumeration (although Scala 3 still supports this too).

* https://github.com/pjfanning/fury-scala-test/blob/main/src/main/scala-3/io/github/pjfanning/fury/ColorEnum.scala
* https://github.com/pjfanning/fury-scala-test/blob/d4e9b067878cb817a86a5d3225df69ce02e427c5/src/test/scala-3/io/github/pjfanning/fury/FuryEnum3Test.scala

Fails with NPE in Fury code.

```
[info] - should serialize/deserialize ColorEnum *** FAILED ***
[info]   java.lang.RuntimeException: Create sequential serializer failed, 
[info] class: class io.github.pjfanning.fury.ColorEnum$$anon$1
[info]   at io.fury.serializer.CodegenSerializer.loadCodegenSerializer(CodegenSerializer.java:46)
[info]   at io.fury.resolver.ClassResolver.lambda$getObjectSerializerClass$2(ClassResolver.java:943)
[info]   at io.fury.builder.JITContext.registerSerializerJITCallback(JITContext.java:132)
[info]   at io.fury.resolver.ClassResolver.getObjectSerializerClass(ClassResolver.java:941)
[info]   at io.fury.resolver.ClassResolver.getObjectSerializerClass(ClassResolver.java:922)
[info]   at io.fury.serializer.ReplaceResolveSerializer.newJDKMethodInfoCache(ReplaceResolveSerializer.java:162)
[info]   at io.fury.serializer.ReplaceResolveSerializer.<init>(ReplaceResolveSerializer.java:203)
[info]   at io.fury.serializer.Serializers.newSerializer(Serializers.java:80)
[info]   at io.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1154)
[info]   at io.fury.resolver.ClassResolver.getOrUpdateClassInfo(ClassResolver.java:1095)
[info]   ...
[info]   Cause: java.lang.NullPointerException:
[info]   at io.fury.codegen.CodegenContext.type(CodegenContext.java:289)
[info]   at io.fury.codegen.CodegenContext.namePrefix(CodegenContext.java:260)
[info]   at io.fury.codegen.CodegenContext.newName(CodegenContext.java:178)
[info]   at io.fury.builder.ObjectCodecBuilder.buildEncodeExpression(ObjectCodecBuilder.java:143)
[info]   at io.fury.builder.BaseObjectCodecBuilder.genCode(BaseObjectCodecBuilder.java:203)
[info]   at io.fury.codegen.CompileUnit.getCode(CompileUnit.java:54)
[info]   at io.fury.codegen.JaninoUtils.toBytecode(JaninoUtils.java:73)
[info]   at io.fury.codegen.JaninoUtils.toBytecode(JaninoUtils.java:65)
[info]   at io.fury.codegen.CodeGenerator.compile(CodeGenerator.java:141)
[info]   at io.fury.builder.CodecUtils.loadOrGenCodecClass(CodecUtils.java:89)
[info]   ...
```

**Comment by chaokunyang** [comment]
@pjfanning I can't run [FuryEnum3Test.scala](https://github.com/pjfanning/fury-scala-test/blob/d4e9b067878cb817a86a5d3225df69ce02e427c5/src/test/scala-3/io/github/pjfanning/fury/FuryEnum3Test.scala). Do I need to do any changes about `build.sbt`.

Here is may configuration:
```sbt
name := "fury-scala-test"

scalaVersion := "3.3.1"
crossScalaVersions := Seq("2.12.18", "2.13.12", "3.3.1")

val furyVersion = "0.2.1"

//resolvers ++= Resolver.sonatypeOssRepos("snapshots")

libraryDependencies ++= Seq(
  "org.furyio" % "fury-core" % furyVersion,
  "org.scalatest" %% "scalatest" % "3.2.17",
  "org.slf4j" % "slf4j-simple" % "2.0.9" % Test
)

unmanagedSourceDirectories in Compile += (baseDirectory( _ / "src" / "main" / "scala-3" )).value

Test / unmanagedSourceDirectories ++= {
  Seq(
    (LocalRootProject / baseDirectory).value / "src" / "test" / "scala-3"
  )
}


```

**Comment by pjfanning** [comment]
Latest versions of sbt automatically handle `scala-3` source folders - i.e. you don't need to define `unmanagedSourceDirectories` for them.

If you check out latest main branch of https://github.com/pjfanning/fury-scala-test then this command will reproduce this issue:

`sbt ++3.3 test`

or

`sbt ++3.3 "testOnly io.github.pjfanning.fury.FuryEnum3Test"`

**Comment by pjfanning** [comment]
The issue in Fury CodegenContext.java is that it calls `String type = clz.getCanonicalName();`. This can return `null` but Fury fails to handle `null`s.

getCanonicalName Javadoc says this:
```
Classes without canonical names include:
a local class
a anonymous class
a hidden class
an array whose component type does not have a canonical name
```

The problem class here is an anonymous class - `io.github.pjfanning.fury.ColorEnum$$anon$1`. Scala Compiler loves creating anonymous classes.

**Comment by chaokunyang** [comment]
I still can't run it in IDEA, comand line run is OK. I copied your code and pasted it into a new scala 3 project, works now.

**Comment by chaokunyang** [comment]
I found a strange thing in scala 3 compiler:
![image](https://github.com/alipay/fury/assets/12445254/d09d2f34-133d-49c1-a157-755acab1c6cd)

Scala 3 compiler created a static local class, is this legal in java language specification?

**Comment by chaokunyang** [comment]
@pjfanning I fixed local static class jit bug in https://github.com/alipay/fury/pull/1036, tested with scala3 enum, works fine. But I can't create a local static class in java for test. Do you know how to do it?

**Comment by pjfanning** [comment]
@chaokunyang I don't know how to create a local static class in Java. One option would be to create a module that compiles Scala classes and you could use those classes in your Java project.

**Comment by chaokunyang** [comment]
I see, thanks. I'll merge https://github.com/alipay/fury/pull/1036 first. Maybe we can setup a scala module in https://github.com/alipay/fury/tree/main/scala , and put those tests here? In the long run, scala optimization can be put there too.

**Comment by chaokunyang** [comment]
@pjfanning Would you like to help to setup fury scala module? I think we can setup basic scala project structure in `fury/scala` directory, add basic tests for common scala classes, and add optimization in future.
