### ISSUE TITLE
[Java] Suppress `register class warning` when `requireClassRegistration=false`

### ISSUE THREAD

**Issue by andyczerwonka** [alipay/fury#1083]
When I set the `requireClassRegistration` directive to false, I'm inundated with a lot of non-registration warnings from the `io.fury.resolver.ClassResolver` logger. Given the directive states that we acknowledge we don't required registration, the logs suggest there is a problem.

**Comment by chaokunyang** [comment]
@andyczerwonka This is an issue other users faced with too, I will fix it in https://github.com/alipay/fury/pull/1084
