### ISSUE TITLE
[C++] About the confusing C++ standard used in fury

### ISSUE THREAD

**Issue by PragmaTwice** [alipay/fury#1089]
I notice that there is some inconsistency regarding to the C++ standard used in this library:
- in `.bazelrc`, `-std=c++17` is added in cxxflags,
- in `bazel/fury.bzl`, there is a command line option `-std=c++11`.

If the library uses some post-c++11 features, there may be confusion during the build: 
one may be able to compile according to the `.bazelrc` settings, but another may not.

May I ask if it is possible to clarify the standard?

**Comment by chaokunyang** [comment]
c++17 should be used in `bazel/fury.bzl` too, it's missed in #859. Thanks for this catch.

**Comment by PragmaTwice** [comment]
Thank you for your clarification! I've open a PR to fix it.
