### ISSUE TITLE
[Rust] Cargo test failed 

### ISSUE THREAD

**Issue by caicancai** [alipay/fury#1132]
Thank you for reporting the problem!
Please make sure what you are reporting is a bug with reproducible steps. 

**Describe the bug**

<img width="850" alt="屏幕截图 2023-11-23 115754" src="https://github.com/alipay/fury/assets/77189278/694451ed-2019-4481-aaf3-2413cf658a84">

<img width="541" alt="285092302-41bd2389-284c-405f-bc25-2cef80fdd57d" src="https://github.com/alipay/fury/assets/77189278/a4cbdb8b-b9fa-4c09-8e89-2fd20b14f43d">

**Expected behavior**

**To Reproduce**
Steps to reproduce the behavior.
Please try to provide a reproducible script.

**Screenshots**

**Environment (please complete the following information):**
Please specify the versions of Fury, OS, and others such as JDK/Python/Gcc/Clang/Go/NodeJS if they are used.

**Comment by wangweipeng2** [comment]
@caicancai  The cause of this bug is that I removed the native skip when checking the language flag. I added it back and the cargo test ran successfully. However, the cause of the error that broke the CI pipeline still needs to be investigated."
