### ISSUE TITLE
[Java] CompatibleMode.SCHEMA_CONSISTENT not work as expected

### ISSUE THREAD

**Issue by mof-dev-3** [alipay/fury#1188]
## Is your feature request related to a problem? Please describe.
We use Fury to codec cache objects in Redis and find that CompatibleMode.SCHEMA_CONSISTENT can save us a lot of storage. However, the following test case shows that the SCHEMA_CONSISTENT mode works more like 'COMPACT' mode instead of 'STRICT' mode when the schema is changed.
![企业微信截图_17013944589784](https://github.com/alipay/fury/assets/129163631/840d42d3-b6c2-4e30-b42f-eb2b6639f0ac)

![企业微信截图_17013946051143](https://github.com/alipay/fury/assets/129163631/6d115e81-b172-4043-b620-7bc88baa0bfe)

## AfterThought
For security and consistency's sake, in some cases, 'STRICT' mode is needed (maybe write a schema hash in the serialized bytes) to check whether the schema has changed and report an error when deserializing.

## How to Reproduce
`
    private static final File cachedPerson = new File("cachePerson");

    private static Fury initConsistFury() {
        return Fury.builder()
                .requireClassRegistration(false)
                .withLanguage(Language.JAVA)
                .withCompatibleMode(CompatibleMode.SCHEMA_CONSISTENT)
                .build();
    }
    
    @Test
    public void testBeforeSchemaChange() {
        Fury f = initConsistFury();
        TestPerson p = new TestPerson();
        p.setFirstName("Tom");
        p.setAge(22);
        byte[] bytes = f.serialize(p);
        FileUtil.writeBytes(bytes, cachedPerson);
    }

    @Getter
    @Setter
    @NoArgsConstructor
    @ToString
    public static class TestPerson {
//        private String firstName;
                private String secondName;
//        private Integer age;
                private Integer newInt;
    }

    @Test
    public void testAfterSchemaChange() {
        Fury f = initConsistFury();
        byte[] bytes = FileUtil.readBytes(cachedPerson);
        Object deserialize = f.deserialize(bytes);
        System.out.println(deserialize);
    }

`

**Comment by chaokunyang** [comment]
You can configure fury to write class schema hash by invoking FuryBuilder#withClassVersionCheck.

Would you like to add this part to fury doc?

**Comment by chaokunyang** [comment]
> It may have forward/backward compatibility issue, but default value of checkClassVersion to be true if CompatibleMode.SCHEMA_CONSISTENT is set is more intuitive and heuristic.

This will introduce 4bytes overhead for every object, so we disabled it by default
