### ISSUE TITLE
[<Fury component: Java>] Example in readme has runtime exception

### ISSUE THREAD

**Issue by yeoleobun** [alipay/fury#653]
**Describe the bug**

Code example of Cross-language object graph serialization in Java has Runtime exception.

https://github.com/alipay/fury/blob/main/README.md?plain=1#L176

**Expected behavior**

Complete without exception.

**To Reproduce**

mvn exec:java -Dexec.mainClass="io.fury.examples.ReferenceExample"

**Screenshots**

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java (default-cli) on project fury: An exception occurred while executing the Java class. class com.google.common.collect.RegularImmutableMap is not registered, if it's not the type you want to serialize, it may be a **vulnerability**. If it's not a vulnerability, registering class by `Fury#register` will have better performance, otherwise class name will be serialized too. -> [Help 1]

**Environment (please complete the following information):**

openjdk 17.0.7 

**Fix**

 `
fury.register(Class.forName("com.google.common.collect.RegularImmutableMap"),"com.google.common.collect.RegularImmutableMap");
`

**Comment by chaokunyang** [comment]
@yeoleobun Thanks for filing this issue, the example enabled secure mode, but we didn't register guava types in advance, since common guava types are not public. I submit a PR to register those type in advance in #654, the example works fine with that pr.

**Comment by chaokunyang** [comment]
Feel free to reopen this issue if it still throws exception
