### ISSUE TITLE
java|how to sovle install dependency

### ISSUE THREAD

**Issue by kento996** [alipay/fury#660]
<img width="923" alt="image" src="https://github.com/alipay/fury/assets/72925466/726430ba-6b46-4a97-87ce-6bb8a63556ea">

**Comment by chaokunyang** [comment]
> <img alt="image" width="923" src="https://user-images.githubusercontent.com/72925466/253742872-726430ba-6b46-4a97-87ce-6bb8a63556ea.png">

sonatype disabled , use `https://s01.oss.sonatype.org/content/repositories/snapshots` instead.
![image](https://github.com/alipay/fury/assets/12445254/2924f253-4672-4863-812f-568d65d8f0e6)

We'll upload jars to maven Central in next weeks.
