### ISSUE TITLE
[java]如何开启安全模式

### ISSUE THREAD

**Issue by kento996** [alipay/fury#663]
<img width="677" alt="image" src="https://github.com/alipay/fury/assets/72925466/fb17a95b-7a37-46cf-9c39-3bd325519507">

**Comment by chaokunyang** [comment]
You can enable it by FuryBuilder#withSecureMode api

**Comment by kento996** [comment]
> You can enable it by FuryBuilder#withSecureMode api

thanks！

**Comment by chaokunyang** [comment]
FYI, we just replaced `withSecureMode` by `requireClassRegistration` in https://github.com/alipay/fury/pull/768
