### ISSUE TITLE
Is fury suitable for json or jdk7

### ISSUE THREAD

**Issue by zhugw** [alipay/fury#668]
通过infoq了解到的https://mp.weixin.qq.com/s/1oIws299oIL5YV71SVD7gQ 老实说能用在哪些场景 还不是特别的清楚

比如 我这边有如下场景 

1. 客户端Http上报json数据到服务端 
 json报文比较大 有140K 像这种场景 能压缩json报文吗 减少带宽消耗 同时 服务端解析json的时候能加快效率

2. 一个遗留项目
还是jdk1.7版本 
服务端发送二进制数据
```
// 发送行情数据
try (GZIPOutputStream gzos = new GZIPOutputStream(socket.getOutputStream());
     ObjectOutputStream oos = new ObjectOutputStream(gzos)) {
    Map<Integer, Object> data = new HashMap<>();
    data.put(3, IndexMessageParse.getIndCode2IndexMap());
    data.put(2, StockBondFundBondRepuMessageParse.getStkCode2StockMap());
    oos.writeObject(data);
    oos.flush();
} catch (IOException e) {
    log.error("Send data failed", e);
}
```
客户端接收二进制数据
```
socket = new Socket(IP, PORT);
socket.setSoTimeout(60000);
gzis = new GZIPInputStream(socket.getInputStream());
ois = new ObjectInputStream(gzis);
Map<Integer, Object> result = (Map<Integer, Object>) ois.readObject();
cache.setSzseRealTime(result);
```
客户端部署的机器只有2核 导致CPU经常飙高 原因就是二进制数据的解析

不知道上述2种场景能否使用fury？

**Comment by chaokunyang** [comment]
> 

We don't have plan for json support, there are so many mature json parsing library.

The case2 can be optimized by fury, but minimal jdk version that fury support is JDK8, we used lots lambda/streams API in our codebase.
