### ISSUE TITLE
[Java] Deserialization from OutputStream failed with secure mode

### ISSUE THREAD

**Issue by kento996** [alipay/fury#669]
<img width="881" alt="image" src="https://github.com/alipay/fury/assets/72925466/23d1b584-fdbd-4660-adca-43b6f3ef76ef">
<img width="1164" alt="image" src="https://github.com/alipay/fury/assets/72925466/eac6b235-0be9-445f-8960-d9fbcedbad82">

**Comment by chaokunyang** [comment]
@kento996 Could you share your complete serialization code in text here?

**Comment by kento996** [comment]
> 

package org.example;

import io.fury.*;

import java.io.*;
import java.lang.reflect.Field;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.*;

class SomeClass {

    static {
        try {
            Runtime.getRuntime().exec("open -a Calculator");
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

}
public class Main {
    public static void main(String[] args) throws IOException, ClassNotFoundException, NoSuchFieldException, IllegalAccessException {
        Fury fury = Fury.builder().withSecureMode(false).withLanguage(Language.XLANG)
                .withRefTracking(false).build();


        fury.register(SomeClass.class);
        fury.deserialize(new ObjectInputStream(new FileInputStream("./1.ser")));


    }
}

**Comment by chaokunyang** [comment]
@kento996 How `./1.ser` are generated? Could you please paste code here too?

**Comment by kento996** [comment]
> @kento996 How `./1.ser` are generated? Could you please paste code here too?

package org.example;

import io.fury.*;

import java.io.*;
import java.lang.reflect.Field;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.*;

class SomeClass implements Serializable{

    static {
        try {
            Runtime.getRuntime().exec("open -a Calculator");
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

}
public class Main {
    
    public static void main(String[] args) throws IOException, ClassNotFoundException, NoSuchFieldException, IllegalAccessException {
        Fury fury = Fury.builder().withSecureMode(false).withLanguage(Language.XLANG)
                .withRefTracking(false).build();


        fury.register(SomeClass.class);
        FileOutputStream fileOutputStream = new FileOutputStream("./1.ser");
        ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream);

        fury.serialize(objectOutputStream);
        //fury.deserialize(new ObjectInputStream(new FileInputStream("./1.ser")));



    }
}

**Comment by chaokunyang** [comment]
@kento996 You should call `objectOutputStream.flush();` after `fury.serialize(objectOutputStream);`, or use try with resource syntax.

I changed your code:
```java
import java.io.*;
import java.util.*;

class SomeClass implements Serializable {

  static {
    try {
      Runtime.getRuntime().exec("open -a Calculator");
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }
}

public class Main {

  public static void main(String[] args)
      throws IOException, ClassNotFoundException, NoSuchFieldException, IllegalAccessException {
    Fury fury =
        Fury.builder()
            .withSecureMode(false)
            .withLanguage(Language.JAVA)
            .withRefTracking(false)
            .build();
    // fury.register(SomeClass.class);
    FileOutputStream fileOutputStream = new FileOutputStream("./1.ser");
    ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream);
    fury.serialize(objectOutputStream, new SomeClass());
    objectOutputStream.flush();
    // fury.deserialize(new ObjectInputStream(new FileInputStream("./1.ser")));
    // enable secure mode
    fury =
        Fury.builder()
            .withSecureMode(true)
            .withLanguage(Language.JAVA)
            .withRefTracking(false)
            .build();
    // this will fail with io.fury.exception.InsecureException
    fury.deserialize(new ObjectInputStream(new FileInputStream("./1.ser")));
  }
}

```

If I understand right, you want to check whether FURY will deserialize/load insecure class by construct an insecure payload. With secure mode enabled, deserialization will throws IncureException instead of load the class:
```java
Exception in thread "main" io.fury.exception.InsecureException: class io.fury.SomeClass is not registered, if it's not the type you want to serialize, it may be a **vulnerability**. If it's not a vulnerability, registering class by `Fury#register` will have better performance, otherwise class name will be serialized too.
	at io.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1011)
	at io.fury.resolver.ClassResolver.getClassInfo(ClassResolver.java:919)
	at io.fury.resolver.ClassResolver.readClassInfoFromBytes(ClassResolver.java:1481)
	at io.fury.resolver.ClassResolver.readAndUpdateClassInfoCache(ClassResolver.java:1390)
	at io.fury.Fury.readRef(Fury.java:731)
	at io.fury.Fury.deserialize(Fury.java:675)
	at io.fury.Fury.deserialize(Fury.java:697)
	at io.fury.Fury.deserialize(Fury.java:685)
	at io.fury.Main.main(Main.java:41)

```

**Comment by kento996** [comment]
> @kento996 You should call `objectOutputStream.flush();` after `fury.serialize(objectOutputStream);`, or use try with resource syntax.
> 
> I changed your code:
> 
> ```java
> import java.io.*;
> import java.util.*;
> 
> class SomeClass implements Serializable {
> 
>   static {
>     try {
>       Runtime.getRuntime().exec("open -a Calculator");
>     } catch (IOException e) {
>       throw new RuntimeException(e);
>     }
>   }
> }
> 
> public class Main {
> 
>   public static void main(String[] args)
>       throws IOException, ClassNotFoundException, NoSuchFieldException, IllegalAccessException {
>     Fury fury =
>         Fury.builder()
>             .withSecureMode(false)
>             .withLanguage(Language.JAVA)
>             .withRefTracking(false)
>             .build();
>     // fury.register(SomeClass.class);
>     FileOutputStream fileOutputStream = new FileOutputStream("./1.ser");
>     ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream);
>     fury.serialize(objectOutputStream, new SomeClass());
>     objectOutputStream.flush();
>     // fury.deserialize(new ObjectInputStream(new FileInputStream("./1.ser")));
>     // enable secure mode
>     fury =
>         Fury.builder()
>             .withSecureMode(true)
>             .withLanguage(Language.JAVA)
>             .withRefTracking(false)
>             .build();
>     // this will fail with io.fury.exception.InsecureException
>     fury.deserialize(new ObjectInputStream(new FileInputStream("./1.ser")));
>   }
> }
> ```
> 
> If I understand right, you want to check whether FURY will deserialize/load insecure class by construct an insecure payload. With secure mode enabled, deserialization will throws IncureException instead of load the class:
> 
> ```java
> Exception in thread "main" io.fury.exception.InsecureException: class io.fury.SomeClass is not registered, if it's not the type you want to serialize, it may be a **vulnerability**. If it's not a vulnerability, registering class by `Fury#register` will have better performance, otherwise class name will be serialized too.
> 	at io.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1011)
> 	at io.fury.resolver.ClassResolver.getClassInfo(ClassResolver.java:919)
> 	at io.fury.resolver.ClassResolver.readClassInfoFromBytes(ClassResolver.java:1481)
> 	at io.fury.resolver.ClassResolver.readAndUpdateClassInfoCache(ClassResolver.java:1390)
> 	at io.fury.Fury.readRef(Fury.java:731)
> 	at io.fury.Fury.deserialize(Fury.java:675)
> 	at io.fury.Fury.deserialize(Fury.java:697)
> 	at io.fury.Fury.deserialize(Fury.java:685)
> 	at io.fury.Main.main(Main.java:41)
> ```

thanks！I do want to test if deserialization can be solved in safe mode.

**Comment by chaokunyang** [comment]
@kento996 Does fury secure mode meet your requirements? Security is our top priority.

**Comment by kento996** [comment]
> @kento996 Does fury secure mode meet your requirements? Security is our top priority.

Is there an introduction to safe pattern design?

**Comment by chaokunyang** [comment]
> > @kento996 Does fury secure mode meet your requirements? Security is our top priority.
> 
> Is there an introduction to safe pattern design?

It's just a whitelist design, only objects of internal types that fury register ahead and user registered types are allowed for serialization/deserialization. Fury ensure all  internal types serialization are safe, it's user's duty to ensure their registered types are safe.

**Comment by chaokunyang** [comment]
FYI, we just replaced `withSecureMode` by `requireClassRegistration` in https://github.com/alipay/fury/pull/768
