### ISSUE TITLE
When will the release version be published?

### ISSUE THREAD

**Issue by shopenhe** [alipay/fury#679]

**Comment by chaokunyang** [comment]
alpha release will be published in this week, we'd like to collect more feedbacks before publishing `v0.1.0`

**Comment by chaokunyang** [comment]
Released `v0.1.0-alpha.1` in #693

**Comment by chaokunyang** [comment]
@shopenhe Released fury [v0.1.0](https://github.com/alipay/fury/releases/tag/v0.1.0) , please let use know if you have further issue
