### ISSUE TITLE
[Java] ThreadSafeFury can not register class?

### ISSUE THREAD

**Issue by shopenhe** [alipay/fury#704]
```
{
      ThreadSafeFury fury = Fury.builder().withLanguage(Language.JAVA)
        // Allow to deserialize objects unknown types,
        // more flexible but less secure.
        // .withSecureMode(false)
        .withRefTracking(true)
        .buildThreadSafeFury();
      byte[] bytes = fury.serialize(object);
      System.out.println(fury.deserialize(bytes));
    }
```

`ThreadSafeFury` hasn't `register()` method.  Maybe could add `withRegister()` method to `Builder`.

**Comment by chaokunyang** [comment]
You can register by :
```java
 ThreadSafeFury fury = new ThreadLocalFury(classLoader -> {
        Fury f = Fury.builder().withLanguage(Language.JAVA)
          .withRefTracking(true).withClassLoader(classLoader).build();
        f.register(SomeClass.class);
        return f;
      });
```

**Comment by chaokunyang** [comment]
Perhaps we can add `register` API to `ThreadSafeFury ` too.

**Comment by shopenhe** [comment]
Yes, should add API, otherwise `buildThreadSafeFury()` is chicken ribs.

**Comment by 65487123** [comment]
为什么多线程使用多个Fury序列化，比单个Fury还慢那么多呢？测了一下，多线程多个Fury并发序列化，同样次数，耗时和使用单个Fury加synchronized锁差不多。那这创建多个Fury也没多大意义啊，白耗那么多资源，还不如加同步锁用一个Fury。。

**Comment by chaokunyang** [comment]
> 为什么多线程使用多个Fury序列化，比单个Fury还慢那么多呢？测了一下，多线程多个Fury并发序列化，同样次数，耗时和使用单个Fury加synchronized锁差不多。那这创建多个Fury也没多大意义啊，白耗那么多资源，还不如加同步锁用一个Fury。。

How do you test the serialization, this is not consist with what we see

**Comment by chaokunyang** [comment]
@chaokunyang How do you test the serialization, this is not consist with what we see

**Comment by chaokunyang** [comment]
ThreadSafe fury don't use multiple thread internally. It's just a fury pooling to avoid lock cost

**Comment by 65487123** [comment]
> How do you test the serialization, this is not consist with what we see
I first serialized and deserialized an object 100,000 times with a single thread and a single Fury, measured the time, about 5000 milliseconds, and then created a thread pool of 8 threads, each thread has a Fury, executed 100,000 serialization deserialization tasks, and waited for the end of the thread pool task. The total time is about 7,000 milliseconds. I used protostuff to test the same logic, multithreaded concurrent serialization deserialization, is faster than a single thread.

**Comment by 65487123** [comment]
> ThreadSafe fury don't use multiple thread internally. It's just a fury pooling to avoid lock cost

I first serialized and deserialized an object 100,00000 times with a single thread and a single Fury, measured the time, about 5000 milliseconds, and then created a thread pool of 8 threads, each thread has a Fury, executed 100,00000 serialization deserialization tasks, and waited for the end of the thread pool task(threadpool.shutdown();threadpoll.awaitTermination()).   The total time is about 7,000+ milliseconds.   I used protostuff to test the same logic, multithreaded concurrent serialization deserialization, is faster than a single thread. (Single-thread serialization and deserialization take 14,000 + milliseconds, and 8-thread parallel serialization and deserialization take about 7,000 milliseconds)

**Comment by 65487123** [comment]
> How do you test the serialization, this is not consist with what we see

I first serialized and deserialized an object 100,00000 times with a single thread and a single Fury, measured the time, about 5000 milliseconds, and then created a thread pool of 8 threads, each thread has a Fury, executed 100,00000 serialization deserialization tasks, and waited for the end of the thread pool task(threadpool.shutdown();threadpoll.awaitTermination()).   The total time is about 7,000+ milliseconds.   I used protostuff to test the same logic, multithreaded concurrent serialization deserialization, is faster than a single thread. (Single-thread serialization and deserialization take 14,000 + milliseconds, and 8-thread parallel serialization and deserialization take about 7,000 milliseconds)

**Comment by chaokunyang** [comment]
> > You can register by :
> > ```java
> >  ThreadSafeFury fury = new ThreadLocalFury(classLoader -> {
> >         Fury f = Fury.builder().withLanguage(Language.JAVA)
> >           .withRefTracking(true).withClassLoader(classLoader).build();
> >         f.register(SomeClass.class);
> >         return f;
> >       });
> > ```
> 
> Just ask a question, what is the role of FuryBuilder#withClassLoader and what are the scenarios used, and whether it is used to reduce the frequent creation of fury instances？

We bind every fury with a classloader, to avoid jit of different classes with same conflict with each other.

**Comment by ye-xiaowei** [comment]
@chaokunyang Can register improve performance or is it just to improve security?

**Comment by chaokunyang** [comment]
> @chaokunyang Can register improve performance or is it just to improve security?
performance will be better too, since class name can be serialized by an ID
