### ISSUE TITLE
[<Fury component: Protocol|Java|Python|C++|JavaScript|etc...>]

### ISSUE THREAD

**Issue by luciagolovin** [alipay/fury#705]

**Comment by wangweipeng2** [comment]
> ## Is your feature request related to a problem? Please describe.
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> ## Describe the solution you'd like
> A clear and concise description of what you want to happen.
> 
> ## Additional context
> Add any other context or screenshots about the feature request here.

😁  forget to paste someting ?

**Comment by chaokunyang** [comment]
@luciagolovin please provide details about what you want
