### ISSUE TITLE
[JavaScript] Serializing a map with 20000 elements, will fail sometimes 

### ISSUE THREAD

**Issue by immatt2015** [alipay/fury#756]
**Describe the bug**
serializing a map with 2w elements failed sometimes.

**Expected behavior**

**To Reproduce**

js code
```
const Fury = require('@furyjs/fury');
const { Type } = Fury;
const hps = require('@furyjs/hps');

const mp = new Map()
for (let i = 0; i < 20000; i++) {
    mp.set(btoa((Math.random() * 10000).toString()), !!i % 2)
}

const description = Type.object('test', {
    value: Type.map(Type.string(), Type.bool())
});

const fury = new Fury.default({ hps });
const { serialize, deserialize } = fury.registerSerializer(description);

const input = serialize({ value: mp });
const result = deserialize(input);

console.log(result.value.size)
```

**Screenshots**
<img width="829" alt="Screenshot 2023-07-25 at 17 36 44" src="https://github.com/alipay/fury/assets/11419393/c94b0b10-c3c6-4d82-a55d-ef58c2afeef9">

**Environment (please complete the following information):**
```
macOs 13.4.1
node v19.6.0
```

**Comment by chaokunyang** [comment]
@wangweipeng2 could you take a look at it?

**Comment by wangweipeng2** [comment]
> **Describe the bug** serializing a map with 2w elements failed sometimes.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **To Reproduce**
> 
> js code
> 
> ```
> const Fury = require('@furyjs/fury');
> const { Type } = Fury;
> const hps = require('@furyjs/hps');
> 
> const mp = new Map()
> for (let i = 0; i < 20000; i++) {
>     mp.set(btoa((Math.random() * 10000).toString()), !!i % 2)
> }
> 
> const description = Type.object('test', {
>     value: Type.map(Type.string(), Type.bool())
> });
> 
> const fury = new Fury.default({ hps });
> const { serialize, deserialize } = fury.registerSerializer(description);
> 
> const input = serialize({ value: mp });
> const result = deserialize(input);
> 
> console.log(result.value.size)
> ```
> 
> **Screenshots** <img alt="Screenshot 2023-07-25 at 17 36 44" width="829" src="https://user-images.githubusercontent.com/11419393/255858392-c94b0b10-c3c6-4d82-a55d-ef58c2afeef9.png">
> 
> **Environment (please complete the following information):**
> 
> ```
> macOs 13.4.1
> node v19.6.0
> ```
Thank you for submitting the issue, it is a bug. The buffer space is calculated when generating JavaScript code. We made some adjustments to the protocol a few days ago, which caused the space calculation to be incorrect. I will fix it and add buffer space calculation test cases to ensure that it does not happen again in the future.
