### ISSUE TITLE
[Scala] optimize scala singleton `object` serialization

### ISSUE THREAD

**Issue by chaokunyang** [alipay/fury#764]
scala `object` singleton defines `writeReplace` method, which returns scala.runtime.ModuleSerializationProxy. Fury didn't fastpath this, and it's not efficient.

```scala
object Foo {
}
```

![image](https://github.com/alipay/fury/assets/12445254/1cd34057-80a6-4bd5-b693-fbe9606a3db2)
![image](https://github.com/alipay/fury/assets/12445254/51e84832-7c4d-4cee-8a70-3e68dc70d491)

**Comment by pjfanning** [comment]
Without specialized support for singleton instances, fury is likely to create separate instances when it deserializes the singleton instead of trying to return the singleton instance.

If you want to implement something, keep an eye out for the `MODULE$` field that the Scala compiler adds to the generated class. This is a singleton instance.

**Comment by chaokunyang** [comment]
The singleton will be ensured when using fury. Scala compiler added `writePlace` method which return a proxy for serialization, the `readResolve` method of proxy will return the singleton object. Fury support JDK `writeObject/readObject/writeReplace/readResolve/readObjectNoData/Externalizable` serialization API, so the correctness still persists.

But invoke `writeObject/readObject` is not cheap. And keep compatible with JDK API has its space/speed cost. It will be much better if we implement serializer for such class directly. For example:

```java
class ScalaObjectSerializer {
  public void write(memoryBuffer buf, T obj) {}

  public Object write(memoryBuffer buf) {
     return xxx. MODULE$;
  }

}
```

**Comment by pjfanning** [comment]
One other problem might be recognizing when a class represents a Scala Object. There is no shared Java interface that these classes implement. The only reliable approach is to check if the class has a `MODULE$` field. You probably don't want to add this runtime overhead for all Java users. You would probably want some way of enabling and disabling Scala-specific checks like this.

I maintain https://github.com/FasterXML/jackson-module-scala, so I have some experience of supporting Scala in a Java-focused serialization framework (Jackson). It's pretty hard to support Scala classes using just Java reflection and not accidentally interfere with the non-Scala classes accidentally (it is hard to tell them apart when you using Java Reflection only).

**Comment by chaokunyang** [comment]
I see, java reflection is not feasible for such complex work, especially scala has it's own type mechanism and it changes between scala releases .

Thank you very much for taking time to share this  invaluable information. Your insights on scala and experience 
 on excellent https://github.com/FasterXML/jackson-module-scala really helps a lot. Hope we can get your further help in future.

Scala is used widely in distribued systems such as spark/flink/akka. And the serialization between processes when using `datastream/rdd` API is a common bottleneck for such frameworks. If fury can support scala serialization in the way you do in https://github.com/FasterXML/jackson-module-scala and integrate with fury runtime codegen, I think it will make such frameworks much faster and make fury better too. Thank you once again for your valuable input.

**Comment by pjfanning** [comment]
I tested serializing a Scala case object with fury and one thing that might surprise users is the need to register the scala.runtime.ModuleSerializationProxy class as well the object class. This works:

```
      val fury = Fury.builder().withLanguage(Language.JAVA).build()
      fury.register(classOf[ModuleSerializationProxy])
      fury.register(SampleObject.getClass)
      val bytes = fury.serialize(SampleObject)
      fury.deserialize(bytes) shouldBe SampleObject
```

**Comment by chaokunyang** [comment]
You can create fury with requireClassRegistration false, then the registration won't be necessary

**Comment by pjfanning** [comment]
Thanks @chaokunyang. It's useful to be able to disable the class registration but many users would prefer to use it. It might be useful to have a user doc for Scala users that highlight unexpected issues like the need to register classes like scala.runtime.ModuleSerializationProxy when using objects including scala enumerations.

**Comment by chaokunyang** [comment]
Good suggestion, we should have a user doc for scala users. And I am thinking whether we should register those classes in advance if scala objects detected. Common scala classes should be registered in advance if scala serialization optimization is enabled

**Comment by pjfanning** [comment]
I can do some more experimentation. These 2 are needed.
* scala.runtime.ModuleSerializationProxy
* scala.Enumeration.Val

There are probably a few others. I can find out doing some trial and error.

**Comment by chaokunyang** [comment]
Yes, those are needed. I added those to scala doc https://github.com/alipay/fury/pull/102. 

Perhaps common scala collections are needed too
