### ISSUE TITLE
[Java] jdk17 List、Set、Map serializeJavaObject error

### ISSUE THREAD

**Issue by lmm1990** [alipay/fury#820]
error content
```
class java.util.ImmutableCollections$ListN is not registered, if it's not the type you want to serialize, it may be a **vulnerability**. If it's not a vulnerability, registering class by `Fury#register` will have better performance, otherwise class name will be serialized too.
```

problem
java.util.ImmutableCollections is not public，can't register

hope

fury default register

**Comment by chaokunyang** [comment]
Those classes are not registered adhead. You need to register them by object.getClass currently. We will register them ahead in next release
