### ISSUE TITLE
[Java]Object object serialization is not supported

### ISSUE THREAD

**Issue by 65487123** [alipay/fury#826]
Even if Object.class is registered, an exception will still be thrown when serializing Object objects. An exception is also thrown when serializing a registered class with an attribute of type Object.
Protostuff doesn't have this problem. Can it be solved?

**Comment by chaokunyang** [comment]
@65487123 Could you share your code here?

**Comment by chaokunyang** [comment]
I see. java.lang.Objext didn't implements java.io.Serializable. We disabled serialization support for such classes whose package name starts with `java.`

**Comment by 65487123** [comment]
> I see. java.lang.Objext didn't implements java.io.Serializable. We disabled serialization support for such classes whose package name starts with `java.`

So this problem can't be solved? Then this serialization tool is not as widely applicable as protostuff, although the performance is a little higher

**Comment by chaokunyang** [comment]
It's easy to resolve it. I can submit a pr to fix it this day later

**Comment by chaokunyang** [comment]
@65487123 You can invoke FuryBuilder#withJDKSerializableCheck to false and FuryBuilder#requireClassRegistration to false. I believe that will make java.lang.Object Serializable

**Comment by chaokunyang** [comment]
It's not a little faster. It's 20-30× faster. Some one else has tested using gaming data.  See https://blog.csdn.net/jiangguilong2000/article/details/131775858

**Comment by 65487123** [comment]
> @65487123 You can invoke FuryBuilder#withJDKSerializableCheck to false and FuryBuilder#requireClassRegistration to false. I believe that will make java.lang.Object Serializable

Thank you. I tried. It worked. Can consult, jdkClassSerializableCheck what is the meaning of this field? Why not default to false?

Also, I recommend that when an exception is thrown while serializing an Object, there is a prompt in the exception message that instructs the user to set this field to false, after all, many people like me who are using Fury for the first time do not know these details.

**Comment by 65487123** [comment]
> It's not a little faster. It's 20-30× faster. Some one else has tested using gaming data. See https://blog.csdn.net/jiangguilong2000/article/details/131775858

Based on my own measurements, if it is a single-threaded serialization, Fury does have a clear advantage compared to Protostuff, but it is not as exaggerated as ten times, at most it is about three times (based on total time, using JDK 17). However, if it is multithreaded concurrent serialization of objects, the advantage of Fury is not so obvious. First, multiple threads cannot share one Fury, each thread needs its own Fury, which will consume more memory. Secondly, storing and retrieving the Fury exclusively used by different threads also consumes resources, and it is necessary to consider recycling the less frequently used Fury. The static serialization method provided by Protostuff supports concurrent execution itself, without these issues.

Also, I tested several objects myself, and after serializing them into byte[], some of the byte[] generated by Protostuff are smaller than those generated by Fury.

The most important thing is that I think network IO is the main bottleneck in terms of time consumption, so even if serialization is twice as fast, the overall throughput improvement is limited, that's why I said "a little".

**Comment by chaokunyang** [comment]
> jdkClassSerializableCheck

This is for safety, JDK doesn't mark this class as Serializable, fury disabled serialziation for jdk internal classes too. For example, java.lang.Thread didn't implement Serializable, obviously we shouldn't allow such objects to be serialized. 
We can't enumerate which classes are secure, so we just registered a small list of jdk types to be safe, other types needs users check the safety and then register them.

`java.lang.Object` is secure, we should register it ahead.

**Comment by chaokunyang** [comment]
> > It's not a little faster. It's 20-30× faster. Some one else has tested using gaming data. See https://blog.csdn.net/jiangguilong2000/article/details/131775858
> 
> Based on my own measurements, if it is a single-threaded serialization, Fury does have a clear advantage compared to Protostuff, but it is not as exaggerated as ten times, at most it is about three times (based on total time, using JDK 17). However, if it is multithreaded concurrent serialization of objects, the advantage of Fury is not so obvious. First, multiple threads cannot share one Fury, each thread needs its own Fury, which will consume more memory. Secondly, storing and retrieving the Fury exclusively used by different threads also consumes resources, and it is necessary to consider recycling the less frequently used Fury. The static serialization method provided by Protostuff supports concurrent execution itself, without these issues.
> 
> Also, I tested several objects myself, and after serializing them into byte[], some of the byte[] generated by Protostuff are smaller than those generated by Fury.
> 
> The most important thing is that I think network IO is the main bottleneck in terms of time consumption, so even if serialization is twice as fast, the overall throughput improvement is limited, that's why I said "a little".

We didn't multithread using jmh. But `ThreadSafeFury` is using ThreadLocal under the hood, all extra overhead are just the cost of `java.lang.ThreadLocal#get`. Does that have so much cost? We didn't find such gap in our cases.

**Comment by chaokunyang** [comment]
About the serialization performance speedup, it's case by case. https://github.com/alipay/fury/blob/main/docs/benchmarks/serialization/bench_serialize_STRUCT_to_directBuffer_tps.png  is 30x faster than protostuff, but https://github.com/alipay/fury/blob/main/docs/benchmarks/deserialization/bench_deserialize_SAMPLE_from_array_tps.png is only 3x faster than protostuff.

String and bianry serialization will have a copy finally, which will amortise the speedup by fury jit a little. I belive it's in our expection.

**Comment by chaokunyang** [comment]
You can enable `io.fury.Fury.FuryBuilder#withNumberCompressed`,which will make the data smaller. I do have plans to make it further smaller. But I'm afraid we don't have time for this.
