### ISSUE TITLE
Chinese document 404.title

### ISSUE THREAD

**Issue by southliu** [alipay/fury#827]
Thank you for reporting the problem!
Please make sure what you are reporting is a bug with reproducible steps. 

**Describe the bug**
进入文档，选择语言为中文，点击开始按钮，就显示404。
![image](https://github.com/alipay/fury/assets/26358837/fffecd99-182c-4471-b2b2-b1295398fec6)

**Expected behavior**
不出现404界面。

**To Reproduce**
1. 进入https://www.furyio.org ，选择语言为中文（需要英文切中文才能复现）。
![image](https://github.com/alipay/fury/assets/26358837/1e2ff7c2-b7c8-4494-884e-867619b9fe20)
2. 点击开始按钮。
![image](https://github.com/alipay/fury/assets/26358837/ab146d4d-fe42-43be-8bb9-0c4e7cff91d0)
3. 就会出现404.
![image](https://github.com/alipay/fury/assets/26358837/46a63bc4-1b6a-4ece-9df4-f16c381700be)

**Comment by chaokunyang** [comment]
@wangweipeng2 could you take a look at it

**Comment by wangweipeng2** [comment]
> @wangweipeng2 could you take a look at it

The href of the start button is wrong. I will fix it

**Comment by wangweipeng2** [comment]
> Thank you for reporting the problem! Please make sure what you are reporting is a bug with reproducible steps.
> 
> **Describe the bug** 进入文档，选择语言为中文，点击开始按钮，就显示404。 ![image](https://user-images.githubusercontent.com/26358837/257722892-fffecd99-182c-4471-b2b2-b1295398fec6.png)
> 
> **Expected behavior** 不出现404界面。
> 
> **To Reproduce**
> 
> 1. 进入https://www.furyio.org ，选择语言为中文（需要英文切中文才能复现）。
>    ![image](https://user-images.githubusercontent.com/26358837/257723637-1e2ff7c2-b7c8-4494-884e-867619b9fe20.png)
> 2. 点击开始按钮。
>    ![image](https://user-images.githubusercontent.com/26358837/257724067-ab146d4d-fe42-43be-8bb9-0c4e7cff91d0.png)
> 3. 就会出现404.
>    ![image](https://user-images.githubusercontent.com/26358837/257724195-46a63bc4-1b6a-4ece-9df4-f16c381700be.png)


Could you please try it again? I updated the site a few minutes ago.
