### ISSUE TITLE
[Python] Python3.10 wheel not released

### ISSUE THREAD

**Issue by Suyi32** [alipay/fury#858]
Thank you for reporting the problem!
Please make sure what you are reporting is a bug with reproducible steps. 

**Describe the bug**
Cannot install by  `pip install pyfury --pre`

**Expected behavior**

Install pyfury on my machine

**To Reproduce**

In a AWS EC2 instance, run `pip install pyfury --pre`

**Screenshots**

**Environment (please complete the following information):**

In AWS EC2 instance, Ubuntu 20.04, Python 3.10.9, pip 23.2.1 from /home/ubuntu/anaconda3/lib/python3.10/site-packages/pip (python 3.10)

**Comment by Suyi32** [comment]
![image](https://github.com/alipay/fury/assets/24327363/d7f7b94a-3b36-4100-84fe-70ce2ec88bd7)

**Comment by chaokunyang** [comment]
@Suyi32 Thanks for filing this issue, we haven't release wheel for python 3.10. Currently we only release for python3.6~3.9. Fury python relies CAPI of pyarrow==4.0.0 for row format schema and convert to arrow, which doesn't release for python3.10.
We have plan to upgrade to newer pyarrow version in next days.

**Comment by Suyi32** [comment]
Thanks for your timely response. Still get the following errors with Python 3.8.2 and pyarrow==4.0.0
![image](https://github.com/alipay/fury/assets/24327363/226b70a1-a92b-4860-b55a-d9e9e13f3b77)

**Comment by chaokunyang** [comment]
Thanks for tesing again, we missed a shared library. The CI use `pip install -v -e .`, which doesn't cover for `python setup.py bdsitg_wheel`. I fixed it in #862

**Comment by chaokunyang** [comment]
@Suyi32 Could you try it again? We just released `pyfury==0.1.1.a1`
