### ISSUE TITLE
[Java] Add support for dubbo3 

### ISSUE THREAD

**Issue by ilxqx** [alipay/fury#868]

**Comment by chaokunyang** [comment]
Hi @ilxqx , thanks for creating this issue. Dubbo integration is important for fury. I just write an integration for dubbo java: https://github.com/fury-project/dubbo-serialization-fury . Could you try it out?

Currently this is put outside of [dubbo](https://github.com/apache/dubbo) repo. If this work, I can upload it into maven central repo and create a pr in [duubo](https://github.com/apache/dubbo)  in the future.

**Comment by ilxqx** [comment]
Thanks, I'll try it right away
