### ISSUE TITLE
[Java]Regarding deserialization, the variable type is not accurate?

### ISSUE THREAD

**Issue by PisecesPeng** [alipay/fury#872]
## Is your feature request related to a problem? Please describe.
In fact, I roughly compared some common serialization tools locally,
observe the performance of some types, such as `Map<String, Object>`, `List<Object>`, etc..
So far, Fury seems to be accurate in type conversion..
(similar to jackson... , it is not very accurate at some times..)

But I still want to confirm whether Fury's deserialization may be inaccurate in type.
looking forward to your feedback :)

**Comment by chaokunyang** [comment]
@PisecesPeng Thanks for creating this issue. Fury deserialization will be accurate in type. For example, if you serialize a `LinkedList/LinkedHashMap`, you will get a `LinkedList/LinkedHashMap` returned instead of `ArrayList/HashMap`.

Unlike other serialization framework, we support **polymorphism** for all types, any subtypes will be serialized as it is.

**Comment by PisecesPeng** [comment]
@chaokunyang Thanks for the reply😄

I'm planning to use Fury in my service,
wondering if this is recommended in the current version `v0.1.0` ?

**Comment by PisecesPeng** [comment]
> @PisecesPeng Thanks for creating this issue. Fury deserialization will be accurate in type. For example, if you serialize a `LinkedList/LinkedHashMap`, you will get a `LinkedList/LinkedHashMap` returned instead of `ArrayList/HashMap`.
> 
> Unlike other serialization framework, we support **polymorphism** for all types, any subtypes will be serialized as it is.

Sorry, It may be that my expression is not clear, so I want to emphasize it
I actually want to ask, on the premise that `Object` is defined as a type,
In objects like `Map<String, Object>`, I store many different types of value...

Can Fury still deserialize to the correct type?

**Comment by chaokunyang** [comment]
Yes, fury supports it natively.

**Comment by chaokunyang** [comment]
> @chaokunyang Thanks for the reply😄
> 
> I'm planning to use Fury in my service, wondering if this is recommended in the current version `v0.1.0` ?

We will release new version recently. Currently you can use v0.1.0

**Comment by PisecesPeng** [comment]
👍 all right, thx!
