### ISSUE TITLE
io.fury.collection.Maps.HashMap() losts half of datas.

### ISSUE THREAD

**Issue by balin998** [alipay/fury#874]
It losts half of datas.

**Describe the bug**
Map<String, String> f2 = ofHashMap("k1", "v1", "k2", "v2");
System.out.println(f2.size());   // 2 expcetd, but the result is 1.
System.out.println(f2);  // {k1=v1}

**Comment by chaokunyang** [comment]
@balin998 Thanks for submitting this issue, it's a careles bug. I created a pr to fix it in #877
