### ISSUE TITLE
ModuleNotFoundError: No module named 'pyfury.lib.mmh3.mmh3'

### ISSUE THREAD

**Issue by codingl2k1** [alipay/fury#884]
Thank you for reporting the problem!
Please make sure what you are reporting is a bug with reproducible steps. 

**Describe the bug**

After `pip install pyfury`, import pyfury failed:

```python
Python 3.9.18 (main, Aug 28 2023, 07:00:41)
[GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfury
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pyfury/__init__.py", line 15, in <module>
    from pyfury import lib  # noqa: F401 # pylint: disable=unused-import
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pyfury/lib/__init__.py", line 15, in <module>
    from pyfury.lib import mmh3  # noqa: F401 # pylint: disable=unused-import
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/pyfury/lib/mmh3/__init__.py", line 15, in <module>
    from .mmh3 import *  # noqa: F401,F403 # pylint: disable=unused-import
ModuleNotFoundError: No module named 'pyfury.lib.mmh3.mmh3'
```

**Expected behavior**

**To Reproduce**
Steps to reproduce the behavior.
Please try to provide a reproducible script.

**Screenshots**

**Environment (please complete the following information):**
Please specify the versions of Fury, OS, and others such as JDK/Python/Gcc/Clang/Go/NodeJS if they are used.

**Comment by chaokunyang** [comment]
Which pyfury version are you using? I tested on my local machine, works fine:
![image](https://github.com/alipay/fury/assets/12445254/53aabb1b-363f-46e7-a2da-bf5f7557c1b5)

**Comment by chaokunyang** [comment]
@codingl2k1 Macos version included the mmh3 shared library, but linux version missed this file. Thanks for creating this issue, I'll release a new version to fix this.
