### ISSUE TITLE
[Java] Integrating Redis occurs an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by YxYL6125** [alipay/fury#902]
Thank you for reporting the problem!
Please make sure what you are reporting is a bug with reproducible steps. 

**Describe the bug**
When I integrated redis and used fury's serialization, I used the deserialize method to deserialize the bytes[] I got from redis, and an ArrayIndexOutOfBoundsException occurred.

**Expected behavior**
hope that after getting byte[], I can successfully deserialize it into Objectu

Below is my code：

```java
	public Object getWithFury(String key) {
		if (key == null) {
			return null;
		} else {
			byte[] bytes = objectToBytes(redisTemplate.opsForValue().get(key));
			if (bytes == null) {
				return null;
			}
			return fury.deserialize(bytes);
		}
	}

	public boolean setWithFury(String key, Object value, long time) {
		try {
			redisTemplate.opsForValue().set(key, fury.serialize(value), time, TimeUnit.SECONDS);
			return true;
		} catch (Exception e) {
			e.printStackTrace();
			return false;
		}
	}

	private byte[] objectToBytes(Object obj) {
		if (obj == null) {
			return null;
		}
		byte[] bytes = null;
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		ObjectOutputStream sOut;
		try {
			sOut = new ObjectOutputStream(out);
			sOut.writeObject(obj);
			sOut.flush();
			bytes = out.toByteArray();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return bytes;
	}


	@Override
	public List<SchoolInfo> getSchoolInfo(SchoolInfoReq req) {
		//...
		String schoolInfoKey = RedisKey.RedisConstructor.getSchoolInfoKey(qxdm, schoolType, degreeType);

		List<SchoolInfo> schoolInfoRes = (List<SchoolInfo>) redisUtil.getWithFury(schoolInfoKey);
		if (schoolInfoRes == null || schoolInfoRes.size() == 0) {
            //...
			schoolInfoRes = schoolInfoMapper.getSchoolInfoByQxdm(qxdm, convertedType, convertedDegree);
			redisUtil.setWithFury(schoolInfoKey, schoolInfoRes, KEY_TIME_ONE_DAY);
		}

		return schoolInfoRes;
	}
```

Then the code goes wrong here

![image-20230906114512301](https://raw.githubusercontent.com/YxYL6125/imgBad/main/img/image-20230906114512301.png)

## My Env

- JDK17

- ```xml
  <dependency>
      <groupId>org.furyio</groupId>
      <artifactId>fury-core</artifactId>
      <version>0.1.1</version>
   </dependency>
  ```

**Comment by chaokunyang** [comment]
@YxYL6125 Thanks for submitting this issue. Could you provide a reproduction code here? it's hard to locate what's wrong without the code.

Without the code, here are some cases which may cause this exception:
- In a multi-threaded scenario, you created and used single `Fury` across threads instead of `ThreadSafeFury`
- Classes of serialization data are different between serialization and deserialization peer, but you didn't set `FuryBuilder#withCompitibleMode`

**Comment by chaokunyang** [comment]
Unproducable

**Comment by chaokunyang** [comment]
No code for reproduce
