### ISSUE TITLE
How to clone bean?

### ISSUE THREAD

**Issue by zhenrenbumeng** [alipay/fury#910]
I want to clonet bean from ClassA to Class.
But I got error when using fury：`Read class null version 554680066 is not consistent with -454615571`

How to clone bean from ClassA to ClassB using fury?
```
public class Fury3 {
    public static void main(String[] args) {

        ClassA objectA = new ClassA();
        objectA.setName("张三");
        objectA.setAge(16);
        objectA.setAa("aa");

        Fury fury = Fury.builder().withLanguage(Language.JAVA).build();
        fury.register(ClassA.class);
        fury.register(ClassB.class);

        byte[] bytes = fury.serializeJavaObject(objectA);
        ClassB objectB = fury.deserializeJavaObject(bytes, ClassB.class);
        System.out.println(JSONObject.toJSONString(objectB));
    }
}
```

**Comment by chaokunyang** [comment]
Seems your code is wrong, the bytes is the data for ClassA, but you passed ClassB when deserializing
maybe ?:
```java
        ClassA objectA = fury.deserializeJavaObject(bytes, ClassA.class);
```

**Comment by zhenrenbumeng** [comment]
> Seems your code is wrong, the bytes is the data for ClassA, but you passed ClassB when deserializing maybe ?:
> 
> ```java
>         ClassA objectA = fury.deserializeJavaObject(bytes, ClassA.class);
> ```

I want to get a ClassB entity from ClassA, the only question is how to do this.

**Comment by chaokunyang** [comment]
Can you try `CompatibleMode`?
```java
        Fury fury = Fury.builder().withLanguage(Language.JAVA).withCompatibleMode(CompatibleMode.Compatible).build();
```

If schema of `ClassB ` arre different from `ClassA`, then  default mode deserialization will raise error.

**Comment by zhenrenbumeng** [comment]
> @zhenrenbumeng Could you try `CompatibleMode`?
> 
> ```java
>         Fury fury = Fury.builder().withLanguage(Language.JAVA).withCompatibleMode(CompatibleMode.Compatible).build();
> ```
> 
> If schema of `ClassB ` arre different from `ClassA`, then default mode deserialization will raise error.

It works. Thank you very much.

```
        ClassA objectA = new ClassA();
        objectA.setName("张三");
        objectA.setAge(16);
        objectA.setClassAAttr("classAAttr");
        objectA.setMap(ofHashMap("k1", "v1", "k2", "v2"));
        objectA.setList(Arrays.asList("a", "b", "c", "d", "e", "f"));

        Fury fury = Fury.builder().withLanguage(Language.JAVA).withCompatibleMode(CompatibleMode.COMPATIBLE).build();
        fury.register(ClassA.class);
        fury.register(ClassB.class);


        byte[] bytes = fury.serializeJavaObject(objectA);
        ClassB objectB = fury.deserializeJavaObject(bytes, ClassB.class);
        System.out.println(JSONObject.toJSONString(objectB));
        //    {"age":16,"list":["a","b","c","d","e","f"],"map":{"k1":"v1","k2":"v2"},"name":"张三"}
```
