### ISSUE TITLE
[java][0.2.0] java.lang.NoclassDefFoundError: com/google/common/base/Preconditions

### ISSUE THREAD

**Issue by jiangguilong2000** [alipay/fury#996]
when junittest case use the serializeJavaObject API,it throws  exception as following:
> java.lang.NoclassDefFoundError: com/google/common/base/Preconditions
at io.fury.type.Type.<init>(Type.java:169)
at io.fury.type.Type.<clinit>(Type.java:28
at io.fury.Fury.<clinit>(Fury.java:85)
at io.gamioo.sandbox.ProtoTest.beforeAll(ProtoTest.java:44) <31 internal lines>
at java.base/java.util.ArrayList.forEach(ArrayList,java:1541) <23 internal lines>Create breakpoint : com.google.common.basePreconditions <2 internal lines>+Caused by: java.lang.ClassNotFoundExceptionat java.base/javalang.classLoader.loadclass(CassLoader,java:522)
... 59 more

**I hope fury can get rid of this dependency about guava**

```java
Fury fury = Fury.builder().withLanguage(Language.JAVA).withRefTracking(true).requireClassRegistration(false).withNumberCompressed(false).build();
 byte[] bytes = fury.serializeJavaObject(skillFire_s2C_msg);

```

fury version:0.2.0
guava version: 

>  implementation group: 'com.google.guava', name: 'guava', version: '32.1.1-jre'

jdk:

> java -version
openjdk version "11.0.16.1-internal" 2022-08-12
OpenJDK Runtime Environment TencentKonaJDK (build 11.0.16.1-internal+2)
OpenJDK 64-Bit Server VM TencentKonaJDK (build 11.0.16.1-internal+2, mixed mode)

gradle:

------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.16.1-internal (Tencent 11.0.16.1-internal+2)
OS:           Windows 11 10.0 amd64

**Comment by chaokunyang** [comment]
This is a bug in gradle6. You can upgrade gradle to gradle 7. Or add following configs to build.gradle: 
```groovy
sourceSets.all {
  configurations.getByName(runtimeClasspathConfigurationName) {
    attributes.attribute(Attribute.of("org.gradle.jvm.environment", String), "standard-jvm")
  }
  configurations.getByName(compileClasspathConfigurationName) {
    attributes.attribute(Attribute.of("org.gradle.jvm.environment", String), "standard-jvm")
  }
}
```

See https://github.com/google/guava/issues/6612 for more details.

**Comment by chaokunyang** [comment]
In next release we will upgrade guava to newer `32.1.2-jre`, I believe it will resolve the issue too.
